# Generated by Django 4.1.1 on 2022-09-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='period',
            new_name='created',
        ),
    ]
