# Generated by Django 4.1.1 on 2022-09-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_rename_period_price_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
    ]
