# Generated by Django 4.1.1 on 2022-09-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_alter_product_article_alter_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='product_id',
            new_name='product',
        ),
    ]
