# Generated by Django 4.1.1 on 2022-09-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_rename_product_id_price_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturers',
            new_name='Manufacturer',
        ),
    ]
