# Generated by Django 4.1.1 on 2022-10-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_rename_manufacturers_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
