# Generated by Django 4.1.1 on 2022-10-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_remove_product_manufacturer_delete_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.CreateModel(
            name='Stock_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=3, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.stock')),
            ],
            options={
                'verbose_name': 'Продукт на складах',
                'verbose_name_plural': 'Продукты на складах',
            },
        ),
    ]
