# Generated by Django 4.1.1 on 2022-10-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_stock_remove_product_count_stock_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock_product',
            options={'verbose_name': 'Product in stock', 'verbose_name_plural': 'Products in stock'},
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='shopApp.product'),
        ),
    ]
