# Generated by Django 4.1.1 on 2022-10-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0010_alter_stock_product_options_alter_price_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='shopApp.product'),
        ),
        migrations.AlterUniqueTogether(
            name='stock_product',
            unique_together={('product', 'stock')},
        ),
    ]
