# Generated by Django 4.1.1 on 2022-10-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0011_product_description_alter_stock_product_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_Product',
            new_name='StockProduct',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
